[API_KEYS]
OPENAI = ""
GROQ = ""
ANTHROPIC = ""

[API_ENDPOINTS]
OLLAMA = ""
SEARXNG = "http://localhost:8080"

[GENERAL]
PORT = 3001
SIMILARITY_MEASURE = "cosine"

[server]
port = 3001

[database]
path = "/home/perplexica/data/perplexica.db"

[searxng]
api_url = "http://localhost:8080"
